// <auto-generated />
using System;
using APIRest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIRest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250504031805_AgregarCampoPortada")]
    partial class AgregarCampoPortada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIRest.Model.Pelicula", b =>
                {
                    b.Property<int>("IdPelicula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPelicula"));

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaEstreno")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlPortada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPelicula");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            IdPelicula = 1,
                            Director = "Joss Whedon",
                            FechaEstreno = new DateTime(2025, 5, 4, 0, 18, 4, 772, DateTimeKind.Local).AddTicks(5648),
                            Sinopsis = "bla bla",
                            Titulo = "Los Vengadores",
                            UrlPortada = "https://www.futuro.cl/wp-content/uploads/2019/03/avengers-endgame-poster.jpg"
                        },
                        new
                        {
                            IdPelicula = 2,
                            Director = "Mike Newell",
                            FechaEstreno = new DateTime(2025, 5, 4, 0, 18, 4, 772, DateTimeKind.Local).AddTicks(5670),
                            Sinopsis = "bla bla bla",
                            Titulo = "Harry Potter y el caliz de fuego",
                            UrlPortada = "https://www.mubis.es/media/movies/1456/170565/harry-potter-y-el-caliz-de-fuego-l_cover.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
